"""
models/story.py
---------------
ORM models for the story graph: `Story` (the container) and `StoryNode`
(individual narrative beats / decision points).

A story is structured as a tree of nodes:
  - Exactly one node has `is_root=True` (the opening scene).
  - Each node stores its branching choices in the `options` JSON column.
    Each option contains display text and the `node_id` of the next node.
  - Leaf nodes have `is_ending=True`; winning endings additionally set
    `is_winning_ending=True`.

Tables: stories, story_nodes
"""

from sqlalchemy import Boolean, Column, Integer, String, DateTime, Text, ForeignKey, JSON
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from db.database import Base


class Story(Base):
    """
    Top-level container for a generated adventure story.

    Columns
    -------
    id : int
        Auto-incrementing primary key.
    title : str | None
        Human-readable story title generated by the AI.
    session_id : str | None
        Browser/user session that requested the story; used to associate
        stories with users without a full auth system.
    created_at : datetime
        Timestamp (UTC) set automatically when the row is inserted.

    Relationships
    -------------
    nodes : list[StoryNode]
        All narrative nodes that belong to this story.
    """

    __tablename__ = "stories"

    id = Column(Integer, primary_key=True, index=True)
    title = Column(String, nullable=True)
    session_id = Column(String, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    # One story has many nodes; StoryNode.story is the back-reference.
    nodes = relationship("StoryNode", back_populates="story")


class StoryNode(Base):
    """
    A single narrative beat (scene / decision point) within a story.

    The story graph is a tree: the root node is the opening scene, and each
    node's `options` column lists the choices available to the player, each
    pointing to a child node by ID.

    Columns
    -------
    id : int
        Auto-incrementing primary key.
    story_id : int
        Foreign key linking this node to its parent Story.
    content : str | None
        The narrative text displayed to the player for this scene.
    is_root : bool
        True for the single opening node of the story.
    is_ending : bool
        True if this node is a terminal leaf (no further choices).
    is_winning_ending : bool
        True if this ending represents a successful outcome for the player.
        Only meaningful when `is_ending=True`.
    options : list[dict]
        JSON array of choice objects.  Each entry has the shape:
          {"text": "<choice label>", "node_id": <int>}
        where `node_id` is the ID of the next StoryNode to navigate to.
        Empty list for ending nodes.

    Relationships
    -------------
    story : Story
        The parent Story this node belongs to.
    """

    __tablename__ = "story_nodes"

    id = Column(Integer, primary_key=True, index=True)
    story_id = Column(Integer, ForeignKey("stories.id"), index=True)
    content = Column(String, nullable=True)
    is_root = Column(Boolean, default=False)
    is_ending = Column(Boolean, default=False)
    is_winning_ending = Column(Boolean, default=False)
    options = Column(JSON, default=list)  # e.g. [{"text": "Go left", "node_id": 5}]

    story = relationship("Story", back_populates="nodes")


